type Project = {
  name: string;
  headline: string;
  category?: string[];
  achievement?: string[];
  problemStatement?: string;
  solutionApproach?: string;
  startDate?: string;
  endDate?: string;
  status?: string;
  githubUrl?: string;
  liveUrl?: string;
  demoVideo?: string;
  pptImages?: string[];
  projectImages?: string[];
  tags?: string[];
  blogUrl?: string;
  feedbackForm?: string;
  testimonials?: string[];
  challengesFaced?: string[];
  futureScope?: string[];
};


export const projects: Project[]= [
  {
  "name": "Tic Tac Toe",
  "headline": "A classic Tic Tac Toe game built with HTML, CSS, and JavaScript.",
  "category": ["Game", "Web Development"],
  "problemStatement": "Creating an interactive and responsive Tic Tac Toe game for web browsers.",
  "solutionApproach": "Implemented a simple UI with HTML/CSS and game logic with JavaScript.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Game"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Encryptix Landing Page",
  "headline": "A landing page for Encryptix built with HTML and CSS.",
  "category": ["Web Development", "Landing Page"],
  "problemStatement": "Designing a visually appealing and responsive landing page.",
  "solutionApproach": "Used HTML for structure and CSS for styling to create a modern landing page.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "Landing Page"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Discord Clone",
  "headline": "A Discord-like chat application built with Next.js, WebSocket, and Prisma.",
  "category": ["Web Development", "Chat Application"],
  "problemStatement": "Creating a real-time chat application with features similar to Discord.",
  "solutionApproach": "Used Next.js for the frontend, WebSocket for real-time communication, and Prisma for database management.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "WebSocket", "Prisma", "Real-time"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Calculator",
  "headline": "A functional calculator built with HTML, CSS, and JavaScript.",
  "category": ["Web Development", "Utility"],
  "problemStatement": "Building a responsive and interactive calculator for web browsers.",
  "solutionApproach": "Implemented a calculator UI with HTML/CSS and functionality with JavaScript.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Calculator"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Rock Paper Scissor",
  "headline": "A Rock Paper Scissor game built with HTML, CSS, and JavaScript.",
  "category": ["Game", "Web Development"],
  "problemStatement": "Creating an interactive and responsive Rock Paper Scissor game for web browsers.",
  "solutionApproach": "Implemented a simple UI with HTML/CSS and game logic with JavaScript.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Game"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Hotel Website",
  "headline": "A website for a hotel built with HTML and CSS.",
  "category": ["Web Development", "Hospitality"],
  "problemStatement": "Designing a visually appealing and responsive website for a hotel.",
  "solutionApproach": "Used HTML for structure and CSS for styling to create a modern hotel website.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "Hotel", "Website"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Gym Website",
  "headline": "A website for a gym built with HTML and CSS.",
  "category": ["Web Development", "Fitness"],
  "problemStatement": "Designing a visually appealing and responsive website for a gym.",
  "solutionApproach": "Used HTML for structure and CSS for styling to create a modern gym website.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "Gym", "Website"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Gym Website",
  "headline": "A website for a gym built with Next.js.",
  "category": ["Web Development", "Fitness"],
  "problemStatement": "Designing a visually appealing and responsive website for a gym with modern frameworks.",
  "solutionApproach": "Used Next.js for a fast and SEO-friendly gym website.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Gym", "Website"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Amazon Clone",
  "headline": "A clone of Amazon's website built with HTML and CSS.",
  "category": ["Web Development", "E-commerce"],
  "problemStatement": "Replicating the Amazon website's UI with HTML and CSS.",
  "solutionApproach": "Used HTML for structure and CSS for styling to mimic Amazon's design.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "Amazon", "Clone"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Seva Samarth UI",
  "headline": "A UI for Seva Samarth built with HTML, CSS, and JavaScript.",
  "category": ["Web Development", "UI/UX"],
  "problemStatement": "Designing a user-friendly and responsive UI for Seva Samarth.",
  "solutionApproach": "Used HTML/CSS for design and JavaScript for interactivity.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "UI/UX"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Mind Mate",
  "headline": "A quiz-based mental health score application.",
  "category": ["Health", "Web Development"],
  "problemStatement": "Providing users with a mental health score based on quiz responses.",
  "solutionApproach": "Implemented a quiz interface with HTML/CSS/JS and scoring logic.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Mental Health"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "RushLess",
  "headline": "AI-Powered Smart Traffic Management System",
  "category": ["AI", "IoT", "Traffic Management"],
  "problemStatement": "Traffic congestion, inefficient signals, delayed emergency responses, and parking struggles create major urban challenges.",
  "solutionApproach": "Leverages AI, IoT, and real-time data to optimize traffic flow, prioritize emergency vehicles, detect accidents, and provide smart parking solutions.",
  "startDate": "",
  "endDate": "",
  "status": "Finalist at Smart Delhi Ideathon, CodeForge 2.0",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "IoT", "YOLOv8", "Next.js", "MongoDB"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Stock Investment Platform",
  "headline": "A platform showing graphs and data for stock investments built with Next.js.",
  "category": ["Finance", "Web Development"],
  "problemStatement": "Providing users with a visual representation of stock data for better investment decisions.",
  "solutionApproach": "Used Next.js for the frontend and integrated APIs for stock data.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Stock", "Investment", "Graphs"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Pravasi Path",
  "headline": "A web solution to support India's migrant workers built with MERN stack.",
  "category": ["Web Development", "Social Good"],
  "problemStatement": "Addressing critical challenges faced by migrants moving to metro cities in search of employment.",
  "solutionApproach": "Built with MERN stack, plans to integrate AI/ML for job matching and skill development.",
  "startDate": "",
  "endDate": "",
  "status": "Finalist at Build with Delhi",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["MERN", "AI", "ML", "Migrant Workers"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Narrato",
  "headline": "AI-powered storytelling app that generates personalized videos based on user moods.",
  "category": ["AI", "Storytelling", "Mental Health"],
  "problemStatement": "Creating engaging video narratives that reflect user emotions and thoughts.",
  "solutionApproach": "Uses Hugging Face models for script generation, audio generation, and frame generation.",
  "startDate": "",
  "endDate": "",
  "status": "Showcased at AI Horizon Hackathon, NSUT",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Next.js", "Hugging Face", "Remotion"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Hireview",
  "headline": "AI-generated interview questions and candidate evaluation platform.",
  "category": ["AI", "Recruitment"],
  "problemStatement": "Streamlining the interview process with AI-generated questions and real-time feedback.",
  "solutionApproach": "Uses Google Generative AI (Gemini API) for question generation and evaluation.",
  "startDate": "",
  "endDate": "",
  "status": "5th Position at Cube Innovators Hackathon, IIT Delhi",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Next.js", "Gemini", "Recruitment"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "GreenMindAI",
  "headline": "AI-powered waste management platform for tracking, segregating, and recycling waste.",
  "category": ["AI", "Environment", "Waste Management"],
  "problemStatement": "Addressing environmental pollution, inefficient waste collection, and lack of segregation.",
  "solutionApproach": "Uses TensorFlow, YOLOv8 for waste detection, and integrates with municipal systems.",
  "startDate": "",
  "endDate": "",
  "status": "Finalist at Hack Vortex, Clash of Code 2.0, T-Hacks",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "TensorFlow", "YOLOv8", "Waste Management"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Zordie Frontend",
  "headline": "Frontend for Zordie startup built with Next.js and Framer Motion.",
  "category": ["Web Development", "Startup"],
  "problemStatement": "Building a modern and interactive frontend for Zordie startup.",
  "solutionApproach": "Used Next.js for performance and Framer Motion for animations.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Framer Motion", "Startup"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Currency Converter",
  "headline": "A currency converter built with HTML, CSS, and JavaScript.",
  "category": ["Web Development", "Utility"],
  "problemStatement": "Creating a tool to convert currencies in real-time.",
  "solutionApproach": "Used HTML/CSS for UI and JavaScript for conversion logic and API integration.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Currency"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Walmart Hackathon Project",
  "headline": "A project built for Walmart Hackathon using MERN stack.",
  "category": ["Web Development", "Hackathon"],
  "problemStatement": "",
  "solutionApproach": "Used MERN stack (MongoDB, Express, React, Node.js) for the project.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["MERN", "Hackathon", "Walmart"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Drishti",
  "headline": "AI-Powered Public Event Safety Platform",
  "category": ["AI", "Safety", "Public Events"],
  "problemStatement": "Improving safety at large public events with real-time analytics and forecasting.",
  "solutionApproach": "Uses Vertex AI, Gemini, and Google Maps for crowd monitoring and incident response.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Vertex AI", "Gemini", "Safety"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Pulse of Bangalore",
  "headline": "Futuristic 3D Smart City Dashboard",
  "category": ["Web Development", "Smart City"],
  "problemStatement": "Providing real-time city analytics and civic alerts in an immersive 3D dashboard.",
  "solutionApproach": "Used Next.js, Three.js, and Google Gemini API for interactive 3D visuals and AI analytics.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Three.js", "Gemini", "Smart City"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Spark Swipe",
  "headline": "Tinder-style interface for discovering and sharing startup ideas.",
  "category": ["Web Development", "Startup"],
  "problemStatement": "Making idea discovery intuitive and engaging.",
  "solutionApproach": "Used React, Vite, and Framer Motion for a swipe-based UI.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "Framer Motion", "Startup", "Ideas"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "LinkOmatic",
  "headline": "URL to Video Generator",
  "category": ["AI", "Video Generation"],
  "problemStatement": "Transforming web content into engaging videos automatically.",
  "solutionApproach": "Uses Hugging Face models for script generation and Remotion for video stitching.",
  "startDate": "",
  "endDate": "",
  "status": "Finalist in 3 National Hackathons",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Next.js", "Remotion", "Video"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Campus Mate",
  "headline": "AI-powered platform for student life improvement.",
  "category": ["AI", "Education"],
  "problemStatement": "Addressing food waste, lost & found, and cafeteria nutritional insights for students.",
  "solutionApproach": "Uses YOLOv8 for object detection and AI for meal analysis.",
  "startDate": "",
  "endDate": "",
  "status": "Winner – Avinya 2025, NSUT",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "YOLOv8", "Next.js", "Student Life"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "SchedulAI",
  "headline": "Autonomous Meeting Coordinator",
  "category": ["AI", "Productivity"],
  "problemStatement": "Eliminating the back-and-forth of meeting scheduling with AI agents.",
  "solutionApproach": "Uses multi-agent AI negotiation to find optimal meeting times.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Next.js", "Meeting", "Scheduling"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Spotify Player",
  "headline": "Redesigned Spotify player with HTML, CSS, JavaScript, and Spotify API.",
  "category": ["Web Development", "Music"],
  "problemStatement": "Enhancing Spotify's design and functionality with a custom player.",
  "solutionApproach": "Used HTML/CSS/JS for UI and integrated Spotify API for music playback.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript", "Spotify API"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "StayFit",
  "headline": "A sleek and responsive website for gyms, fitness centers, or yoga studios",
  "category": ["Fitness", "Website"],
  "problemStatement": "Gyms and fitness centers need an online presence to showcase services and accept membership inquiries.",
  "solutionApproach": "Provides a responsive website with features like membership plans, class timetables, trainer profiles, and contact forms.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Tailwind CSS"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Mobile Mail OSINT",
  "headline": "A comprehensive OSINT toolkit for phone number analysis",
  "category": ["Security", "OSINT"],
  "problemStatement": "Need for a tool to gather intelligence on phone numbers from various sources.",
  "solutionApproach": "Uses Python FastAPI backend and Next.js frontend to provide detailed phone number analysis with multiple fallback methods.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Python", "FastAPI", "Next.js", "TypeScript"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Share-Hub",
  "headline": "A platform for sharing and renting items",
  "category": ["E-commerce", "Sharing Economy"],
  "problemStatement": "People need a platform to share or rent items locally.",
  "solutionApproach": "Provides a full-featured platform with listings, search, map view, chat, and rental management.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "Supabase"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Veena Agent",
  "headline": "AI Voice Assistant for Insurance",
  "category": ["AI", "Insurance"],
  "problemStatement": "Insurance companies need better customer service solutions.",
  "solutionApproach": "Uses AI to mimic human agents for handling customer queries with natural voice interactions.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "Tailwind CSS", "Vite", "GPT-4", "Gemini"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Kaamly",
  "headline": "Task automation app that handles natural language instructions",
  "category": ["Productivity", "AI"],
  "problemStatement": "People struggle with manual task management and appointment scheduling.",
  "solutionApproach": "Uses AI to understand natural language requests and automate tasks like booking appointments.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Gemini API"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Family Vault",
  "headline": "A secure, collaborative digital vault for family memories",
  "category": ["Storage", "Family"],
  "problemStatement": "Families need a secure way to preserve and share memories across generations.",
  "solutionApproach": "Provides a digital vault with features for uploading, organizing, and sharing family memories.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Prisma"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Bumblebees School",
  "headline": "Website for a playschool with playful frontend design",
  "category": ["Education", "Website"],
  "problemStatement": "Playschools need an engaging online presence to attract parents.",
  "solutionApproach": "Provides a playful, interactive website showcasing the playschool's offerings.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Dharika",
  "headline": "Pre-launch landing page for an Indian ethnic fashion brand",
  "category": ["Fashion", "E-commerce"],
  "problemStatement": "Need to build brand awareness and collect early supporters before launch.",
  "solutionApproach": "Interactive landing page with email capture and gamification to engage potential customers.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "TypeScript", "Tailwind CSS"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Reframe",
  "headline": "Platform for documenting and sharing philosophical evolution",
  "category": ["Social", "Philosophy"],
  "problemStatement": "People need a way to track and share how their beliefs and perspectives change over time.",
  "solutionApproach": "Provides tools to document belief changes, compare before/after views, and engage with a community.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Prisma"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "EcoFleetSim",
  "headline": "Delivery robotics and EV simulation platform",
  "category": ["Simulation", "Logistics"],
  "problemStatement": "Companies need to test delivery strategies without physical hardware.",
  "solutionApproach": "Simulates delivery robots and EVs for route planning and performance analysis.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "Tailwind CSS", "Leaflet.js", "Next.js", "Supabase"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Think Tank",
  "headline": "MERN blog application with admin panel",
  "category": ["Blog", "CMS"],
  "problemStatement": "Need for a customizable blog platform with admin controls.",
  "solutionApproach": "Provides a full-featured blog with admin panel using MERN stack.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["MERN", "MongoDB", "Express", "React", "Node.js"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Swadeshi Scan",
  "headline": "QR-powered platform showing product impact on India's economy",
  "category": ["E-commerce", "Social Impact"],
  "problemStatement": "Consumers lack information about how purchases impact local economy.",
  "solutionApproach": "Uses QR codes to reveal product impact data on jobs, taxes, and environment.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "https://swadeshi-scan.vercel.app/",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "shadcn/ui", "Tailwind CSS", "Gemini"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Health Sync",
  "headline": "AI-Driven Health Ecosystem",
  "category": ["Healthcare", "AI"],
  "problemStatement": "People need integrated health management tools.",
  "solutionApproach": "Combines diagnostics, consultations, e-commerce, and lifestyle guidance in one platform.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Supabase", "AI"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "UpNext",
  "headline": "AI-Powered Career Assistant",
  "category": ["Career", "Education"],
  "problemStatement": "Students need guidance on career paths and skill development.",
  "solutionApproach": "Provides AI-driven career assessment, learning roadmaps, and mentorship.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "Next.js", "Gemini API"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Parity Wars",
  "headline": "Real-time multiplayer game where minority choice wins",
  "category": ["Gaming", "Multiplayer"],
  "problemStatement": "Need for engaging, simple multiplayer games.",
  "solutionApproach": "Creates a game where players choose heads/tails and minority progresses.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "https://github.com/uzumaki-ak/Parity-wars.git",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Socket.io", "Tailwind CSS"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Previous Portfolio",
  "headline": "Personal portfolio website",
  "category": ["Portfolio"],
  "problemStatement": "Need to showcase personal projects and skills.",
  "solutionApproach": "Provides a portfolio website built with Next.js.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Market Agency",
  "headline": "Market agency website for a client",
  "category": ["Marketing", "Website"],
  "problemStatement": "Agency needs professional online presence.",
  "solutionApproach": "Provides a modern website showcasing agency services.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Accernity"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "RSVP",
  "headline": "Platform for event RSVPs",
  "category": ["Events"],
  "problemStatement": "Need for easy event attendance management.",
  "solutionApproach": "Provides a system for managing event RSVPs.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": [],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Lucy Chat Assistant",
  "headline": "AI-powered conversational assistant",
  "category": ["AI", "Chat"],
  "problemStatement": "Need for personalized AI chat assistance.",
  "solutionApproach": "Provides persistent chat interface with AI responses using Gemini API.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "TypeScript", "Tailwind CSS", "MongoDB", "Gemini"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Fin Genie",
  "headline": "Comprehensive AI-driven financial ecosystem",
  "category": ["Finance", "AI"],
  "problemStatement": "Fragmented financial services lack personalization and automation.",
  "solutionApproach": "Provides end-to-end financial management with AI-driven planning, tracking, and optimization.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["AI", "Finance", "Automation"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Hack4Brahma",
  "headline": "Official hackathon website",
  "category": ["Events", "Hackathon"],
  "problemStatement": "Need for a platform to manage and promote a hackathon.",
  "solutionApproach": "Provides a website for hackathon information and registration.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": [],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Digisys",
  "headline": "Modern marketing website",
  "category": ["Marketing", "Website"],
  "problemStatement": "Need for a professional marketing website.",
  "solutionApproach": "Provides a modern website built with Next.js and Accernity.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["Next.js", "Accernity"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Flash Chat",
  "headline": "WhatsApp messaging tool without saving contacts",
  "category": ["Communication"],
  "problemStatement": "Need to chat on WhatsApp without saving contacts.",
  "solutionApproach": "Enables chatting with any number via QR code without saving contacts.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React", "JavaScript", "Bootstrap"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Carbon Footprint Calculator",
  "headline": "Tool to calculate carbon footprint",
  "category": ["Environment"],
  "problemStatement": "People need awareness of their environmental impact.",
  "solutionApproach": "Calculates carbon footprint based on user inputs.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["React"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Old Portfolio",
  "headline": "Previous version of personal portfolio",
  "category": ["Portfolio"],
  "problemStatement": "Need to showcase previous work and skills.",
  "solutionApproach": "Provides a portfolio website.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": [],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Functional Login Page",
  "headline": "Fully functional login page",
  "category": ["Authentication"],
  "problemStatement": "Need for a working login system.",
  "solutionApproach": "Provides a login page with HTML, CSS, and JavaScript.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS", "JavaScript"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
{
  "name": "Ulta Edit Clone",
  "headline": "Clone of Ulta Edit using HTML and CSS",
  "category": ["Clone", "UI"],
  "problemStatement": "Practice recreating existing interfaces.",
  "solutionApproach": "Clones the Ulta Edit interface using HTML and CSS.",
  "startDate": "",
  "endDate": "",
  "status": "",
  "githubUrl": "",
  "liveUrl": "",
  "demoVideo": "",
  "pptImages": [],
  "projectImages": [],
  "tags": ["HTML", "CSS"],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [],
  "futureScope": []
},
]