export type Project = {
  name: string;
  headline: string;
  category?: string[];
  achievement?: string[];
  problemStatement?: string;
  solutionApproach?: string;
  startDate?: string;
  endDate?: string;
  status?: string;
  githubUrl?: string;
  liveUrl?: string;
  demoVideo?: string;
  pptImages?: string[];
  projectImages?: string[];
  tags?: string[];
  blogUrl?: string;
  feedbackForm?: string;
  testimonials?: testimonials[];
  challengesFaced?: string[];
  futureScope?: string[];
};

type testimonials={
  name: string;
  feedback: string;
}

export const projects: Project[] = [
  {
  "name": "DeCognito",
  "headline": "AI-Powered OSINT Platform for Ethical Investigations",
  "category": ["OSINT", "AI", "Cybersecurity"],
  "problemStatement": "In India, ethical investigators, journalists, and cybersecurity professionals lack a unified platform to gather, analyze, and visualize open-source intelligence while ensuring compliance with legal and ethical standards.",
  "solutionApproach": "DeCognito integrates phone intelligence with AI-driven human OSINT. It combines FastAPI, Next.js, and AI models to deliver sentiment analysis, breach detection, social media intelligence, and advanced data visualizations through an ethical, user-friendly platform.",
  "startDate": "2025-07",
  "endDate": "",
  "status": "2xMicrosoft Finalist",
  "githubUrl": "https://github.com/Mohammad-Ehshan/Decognito",
  "liveUrl": "",
  "demoVideo": "https://youtu.be/9wX6ymmzXzE",
  "pptImages": [],
  "projectImages": ["/photosByEhshan/decognito1.png"],
  "tags": [
    "Next.js",
    "FastAPI",
    "AI",
    "OSINT",
    "Cybersecurity",
    "Prisma",
    "Supabase",
    "spaCy",
    "HuggingFace",
    "GeminiAI"
  ],
  "blogUrl": "",
  "feedbackForm": "",
  "testimonials": [],
  "challengesFaced": [
    "Ensuring ethical and legal compliance in OSINT collection.",
    "Handling API rate limits and fallback mechanisms.",
    "Designing an intuitive UI while supporting advanced analytics."
  ],
  "futureScope": [
    "Real-time monitoring and mobile app integration.",
    "Blockchain and crypto transaction analysis.",
    "Dark web monitoring with strict ethical filters.",
    "Enhanced AI-based threat detection."
  ],
  "achievement": [
    "Developed robust fallback system (APIs → scraping → automation).",
    "Built AI pipeline with DistilBERT, ToxicBERT, and Hugging Face models.",
    "Implemented cyberpunk-inspired, matrix-style UI with real-time progress tracking."
  ]
},
 {
    "name": "Spark Swipe",
    "headline": "Tinder-style interface for discovering and sharing startup ideas.",
    "category": ["Web Development", "Startup"],
    "problemStatement": "Making idea discovery intuitive and engaging.",
    "solutionApproach": "Used React, Vite, and Framer Motion for a swipe-based UI.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/Mohammad-Ehshan/SparkSwipe2.0",
    "liveUrl": "https://sparkswipe.netlify.app/",
    "demoVideo": "https://youtu.be/-onxtI0TkxA?si=N_3AZk2YwK_vV1WV",
    "pptImages": [],
    "projectImages": ["/projects/sparkswipe1.png"],
    "tags": ["Mern", "Framer Motion", "Startup", "Ideas"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "LinkOMatic",
    "headline": "URL to Video Generator",
    "category": ["AI", "Video Generation"],
    "problemStatement": "Transforming web content into engaging videos automatically.",
    "solutionApproach": "Uses Hugging Face models for script generation and Remotion for video stitching.",
    "startDate": "",
    "endDate": "",
    "status": "Finalist in 3 National Hackathons",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Link-O-Matic",
    "liveUrl": "https://link-o-matic.vercel.app/",
    "demoVideo": "https://youtu.be/1CUhYGHJwEk",
    "pptImages": [],
    "projectImages": ["/projects/linkomatic1.png"],
    "tags": ["AI", "Next.js", "Remotion", "Video"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Drishti",
    "headline": "AI-Powered Public Event Safety Platform",
    "category": ["AI", "Safety", "Public Events"],
    "problemStatement": "Improving safety at large public events with real-time analytics and forecasting.",
    "solutionApproach": "Uses Vertex AI, Gemini, and Google Maps for crowd monitoring and incident response.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Drishti",
    "liveUrl": "",
    "demoVideo": "https://drive.google.com/file/d/15Wq1S3MCKRCN6WZuiKa7jbOm_edKmDqW/view",
    "pptImages": ["/projects/drishtippt1.png", "/projects/drishtippt2.png", "/projects/drishtippt3.png", "/projects/drishtippt4.png", "/projects/drishtippt5.png", "/projects/drishtippt6.png"],
    "projectImages": ["/projects/drishti1.png"],
    "tags": ["AI", "Vertex AI", "Gemini", "Safety"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
   {
    "name": "Kaamly",
    "headline": "Task automation app that handles natural language instructions",
    "category": ["Productivity", "AI"],
    "problemStatement": "People struggle with manual task management and appointment scheduling.",
    "solutionApproach": "Uses AI to understand natural language requests and automate tasks like booking appointments.",
    "startDate": "",
    "endDate": "",
    "status": "completed",
    "githubUrl": "https://github.com/uzumaki-ak/kaamly",
    "liveUrl": "",
    "demoVideo": "https://youtu.be/OMLiYpTUiuY",
    "pptImages": [],
    "projectImages": ["/projects/kaamly1.png", "/projects/kaamly2.png", "/projects/kaamly3.png"],
    "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Gemini API"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "RushLess",
    "headline": "AI-Powered Smart Traffic Management System",
    "category": ["AI", "IoT", "Traffic Management"],
    "problemStatement": "Traffic congestion, inefficient signals, delayed emergency responses, and parking struggles create major urban challenges.",
    "solutionApproach": "Leverages AI, IoT, and real-time data to optimize traffic flow, prioritize emergency vehicles, detect accidents, and provide smart parking solutions.",
    "startDate": "",
    "endDate": "",
    "status": "3xFinalist",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Rushless",
    "liveUrl": "",
    "demoVideo": "https://drive.google.com/file/d/1K4qwthAsoI-VMZy1RwBq-8OZEntbrC6D/view",
    "pptImages": [],
    "projectImages": ["/projects/rushless1.png"],
    "tags": ["AI", "IoT", "YOLOv8", "Next.js", "MongoDB","FinalistAtSmartDelhiIdeathon","FinalistAtCodeForge"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Pravasi Path",
    "headline": "A web solution to support India's migrant workers built with MERN stack.",
    "category": ["Web Development", "Social Good"],
    "problemStatement": "Addressing critical challenges faced by migrants moving to metro cities in search of employment.",
    "solutionApproach": "Built with MERN stack, plans to integrate AI/ML for job matching and skill development.",
    "achievement": ["Finalist at Build with Delhi Hackathon"],
    "startDate": "2025-05",
    "endDate": "2025-07",
    "status": "Under Development",
    "githubUrl": "https://github.com/Mohammad-Ehshan/PravasiPath",
    "liveUrl": "https://pravasipath.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/Projects/pravasipath1.png"],
    "tags": ["MERN", "AI", "ML", "Migrant Workers","FinalistAtBuildWithDelhi"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "GreenMindAI",
    "headline": "AI-powered waste management platform for tracking, segregating, and recycling waste.",
    "category": ["AI", "Environment", "Waste Management"],
    "problemStatement": "Addressing environmental pollution, inefficient waste collection, and lack of segregation.",
    "solutionApproach": "Uses TensorFlow, YOLOv8 for waste detection, and integrates with municipal systems.",
    "startDate": "",
    "endDate": "",
    "status": "Finalist at Hack Vortex, Clash of Code 2.0, T-Hacks",
    "githubUrl": "https://github.com/Mohammad-Ehshan/GreenMind",
    "liveUrl": "",
    "demoVideo": "https://youtu.be/SrxGfVA_-V8",
    "pptImages": ["/Projects/greenmindppt1.png", "/Projects/greenmindppt2.png", "/Projects/greenmindppt3.png", "/Projects/greenmindppt4.png", "/Projects/greenmindppt5.png", "/Projects/greenmindppt6.png", "/Projects/greenmindppt7.png", "/Projects/greenmindppt8.png", "/Projects/greenmindppt9.png", "/Projects/greenmindppt10.png", "/Projects/greenmindppt11.png", "/Projects/greenmindppt12.png"],
    "projectImages": ["/projects/greenmind1.jpg"],
    "tags": ["AI", "TensorFlow", "YOLOv8", "Waste Management"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Veena Agent",
    "headline": "AI Voice Assistant for Insurance",
    "category": ["AI", "Insurance"],
    "problemStatement": "Insurance companies need better customer service solutions.",
    "solutionApproach": "Uses AI to mimic human agents for handling customer queries with natural voice interactions.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/veena-agent-hack",
    "liveUrl": "https://veena-agent.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/veenaagent1.png"],
    "tags": ["React", "Tailwind CSS", "Vite", "GPT-4", "Gemini"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Narrato",
    "headline": "AI-powered storytelling app that generates personalized videos based on user moods.",
    "category": ["AI", "Storytelling", "Mental Health"],
    "problemStatement": "Creating engaging video narratives that reflect user emotions and thoughts.",
    "solutionApproach": "Uses Hugging Face models for script generation, audio generation, and frame generation.",
    "startDate": "2025-02-23",
    "endDate": "2025-02-23",
    "status": "Showcased at AI Horizon Hackathon, NSUT",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Narrato",
    "liveUrl": "https://narrato-zeta.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/narrato1.png"],
    "tags": ["AI", "Next.js", "Hugging Face", "Remotion"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Hireview",
    "headline": "AI-generated interview questions and candidate evaluation platform.",
    "category": ["AI", "Recruitment"],
    "problemStatement": "Streamlining the interview process with AI-generated questions and real-time feedback.",
    "solutionApproach": "Uses Google Generative AI (Gemini API) for question generation and evaluation.",
    "startDate": "2025-09",
    "endDate": "2025-09",
    "status": "5th Position at Cube Innovators, IIT Delhi",
    "githubUrl": "https://github.com/Mohammad-Ehshan/HireView",
    "liveUrl": "https://hire-view-ehshan.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/hireview1.png"],
    "tags": ["AI", "Next.js", "Gemini", "Recruitment"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Campus Mate",
    "headline": "AI-powered platform for student life improvement.",
    "category": ["AI", "Education"],
    "problemStatement": "Addressing food waste, lost & found, and cafeteria nutritional insights for students.",
    "solutionApproach": "Uses YOLOv8 for object detection and AI for meal analysis.",
    "startDate": "",
    "endDate": "",
    "status": "Winner – Avinya 2025, NSUT",
    "githubUrl": "https://github.com/Mohammad-Ehshan/CollegeMate",
    "liveUrl": "https://college-mate-ehshan.vercel.app/",
    "demoVideo": "https://youtu.be/-nqRIn_0aDc",
    "pptImages": [],
    "projectImages": ["/projects/campusmate1.png"],
    "tags": ["AI", "YOLOv8", "Next.js", "Student Life"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
    {
    "name": "Family Vault",
    "headline": "A secure, collaborative digital vault for family memories",
    "category": ["Storage", "Family"],
    "problemStatement": "Families need a secure way to preserve and share memories across generations.",
    "solutionApproach": "Provides a digital vault with features for uploading, organizing, and sharing family memories.",
    "startDate": "",
    "endDate": "",
    "status": "Completed",
    "githubUrl": "https://github.com/uzumaki-ak/family-vaults",
    "liveUrl": "https://family-vaults.vercel.app/",
    "demoVideo": "https://youtu.be/lIwSNZrEWqc",
    "pptImages": [],
    "projectImages": ["/projects/familyvault1.png"],
    "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Prisma"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "SchedulAI",
    "headline": "Autonomous Meeting Coordinator",
    "category": ["AI", "Productivity"],
    "problemStatement": "Eliminating the back-and-forth of meeting scheduling with AI agents.",
    "solutionApproach": "Uses multi-agent AI negotiation to find optimal meeting times.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/schedual-ai",
    "liveUrl": "https://schedual-ai.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/schedulai1.png"],
    "tags": ["AI", "Next.js", "Meeting", "Scheduling"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
    {
    "name": "Pulse of Bangalore",
    "headline": "Futuristic 3D Smart City Dashboard",
    "category": ["Web Development", "Smart City"],
    "problemStatement": "Providing real-time city analytics and civic alerts in an immersive 3D dashboard.",
    "solutionApproach": "Used Next.js, Three.js, and Google Gemini API for interactive 3D visuals and AI analytics.",
    "startDate": "",
    "endDate": "",
    "status": "Under Development",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Pulse-Of-Bangalore",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/pulseofbangalore1.png"],
    "tags": ["Next.js", "Three.js", "Gemini", "Smart City"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
   {
    "name": "Fin Genie",
    "headline": "Comprehensive AI-driven financial ecosystem",
    "category": ["Finance", "AI"],
    "problemStatement": "Fragmented financial services lack personalization and automation.",
    "solutionApproach": "Provides end-to-end financial management with AI-driven planning, tracking, and optimization.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/fin-genies",
    "liveUrl": "https://fin-genies-kdzp.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/photosByEhshan/fingenie1.png"],
    "tags": ["Fintech", "NextJs", "Automation"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
   {
    "name": "Share-Hub",
    "headline": "A platform for sharing and renting items",
    "category": ["E-commerce", "Sharing Economy"],
    "problemStatement": "People need a platform to share or rent items locally.",
    "solutionApproach": "Provides a full-featured platform with listings, search, map view, chat, and rental management.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/share-hub",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/sharehub1.jpg", "/projects/sharehub2.jpg", "/projects/sharehub3.jpg", "/projects/sharehub4.jpg", "/projects/sharehub5.jpg", "/projects/sharehub6.jpg", "/projects/sharehub7.jpg", "/projects/sharehub8.jpg", "/projects/sharehub9.jpg", "/projects/sharehub10.jpg", "/projects/sharehub11.jpg", "/projects/sharehub12.jpg", "/projects/sharehub13.jpg", "/projects/sharehub14.jpg", "/projects/sharehub15.jpg","/projects/sharehub16.jpg"],
    "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "Supabase"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
   {
    "name": "MindMate",
    "headline": "An AI-powered mental health companion built with Next.js, Tailwind, shadcn/ui, PostgreSQL, and Gemini AI.",
    "category": ["Health", "Web Development", "AI"],
    "problemStatement": "Many individuals struggle to assess and track their mental health over time. Existing solutions lack personalization, real-time adaptability, and data-driven insights.",
    "solutionApproach": "MindMate leverages Gemini AI to engage users in personalized quizzes that assess mental health status. Responses are analyzed in real-time, predictions are generated, and results are stored securely in PostgreSQL for long-term tracking. Clerk authentication ensures secure user access while Tailwind CSS and shadcn/ui provide a clean, responsive interface.",
    "startDate": "2025-02-28",
    "endDate": "2025-02-29",
    "status": "Under Development",
    "githubUrl": "https://github.com/Mohammad-Ehshan/MindMate",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["Next.js", "Tailwind CSS", "shadcn/ui", "PostgreSQL", "Clerk", "Gemini AI"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [
      {
        "name": "Sarah Mitchell",
        "feedback": "MindMate feels like a personal wellness coach — the AI actually adapts to my answers."
      },
      {
        "name": "James Carter",
        "feedback": "Clean interface, insightful results, and I love that it remembers my progress over time."
      }
    ],
    "challengesFaced": [
      "Integrating Gemini AI for real-time, context-aware quiz questions",
      "Ensuring mental health data is stored securely and privately",
      "Creating a responsive UI that is both calming and accessible"
    ],
    "futureScope": [
      "Introduce daily mood tracking and journaling features",
      "Add progress analytics with visual charts",
      "Implement multi-language support for wider accessibility",
      "Integrate professional mental health resources and chat support"
    ]
  },
  {
    "name": "Neura Chat",
    "headline": "A modern, Discord-like real-time chat platform for communities and teams.",
    "category": ["Web Development", "Chat Application"],
    "problemStatement": "Many existing chat platforms are either too complex, lack customization, or are closed-source, making it difficult for developers to build tailored communication solutions. There was a need for a fast, scalable, and customizable chat app with features similar to Discord.",
    "solutionApproach": "Developed Neura Chat using Next.js for a responsive and performant frontend, WebSocket for low-latency real-time messaging, and Prisma for efficient database queries and schema management. Implemented user authentication, server-based chat rooms, and message persistence, along with a sleek, minimal UI.",
    "startDate": "2025-08-01",
    "endDate": "2025-08-30",
    "status": "Completed",
    "githubUrl": "",
    "liveUrl": "https://community-bm72.onrender.com",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/neurachat.png"],
    "tags": ["Next.js", "WebSocket", "Prisma", "Real-time", "TailwindCSS", "TypeScript"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [
      {
        "name": "Alex Johnson",
        "feedback": "Neura Chat is lightning fast and feels just like Discord — but with a cleaner interface!"
      },
      {
        "name": "Maria Lopez",
        "feedback": "Loved the simplicity and speed. Setting up servers and channels was effortless."
      }
    ],
    "challengesFaced": [
      "Ensuring smooth WebSocket reconnections during network drops.",
      "Optimizing database queries to handle large message histories without lag.",
      "Implementing role-based permissions for channels and servers."
    ],
    "futureScope": [
      "Add voice and video call functionality.",
      "Introduce bot integrations for automation.",
      "Mobile app version with offline message caching.",
      "Theme customization for server owners."
    ]
  },
  {
    "name": "E-Learning Platform",
    "headline": "An animated landing page and interactive dashboard for an e-learning platform with real-time analytics and data visualization.",
    "category": ["Web Development", "Landing Page", "Dashboard", "E-Learning"],
    "problemStatement": "Creating a visually engaging and data-driven platform that helps learners track their progress, course completion, and study hours in an intuitive way.",
    "solutionApproach": "Developed a responsive landing page with smooth animations to attract users, and built an analytics dashboard using Chart.js for interactive visualizations. Integrated course completion tracking, progress monitoring, and study hour management to provide actionable learning insights.",
    "startDate": "2025-06-10",
    "endDate": "2025-07-05",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/E-Learning",
    "liveUrl": "https://e-learning-ehshan.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/e-learning.png"],
    "tags": ["HTML5", "CSS3", "JavaScript", "Chart.js", "Data Visualization", "Responsive Design", "E-Learning"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [
      {
        "name": "Sarah Mitchell",
        "feedback": "The dashboard is clean, interactive, and makes tracking my learning progress so easy!"
      },
      {
        "name": "David Lee",
        "feedback": "Loved the animations on the landing page. The progress tracking visuals are incredibly helpful."
      }
    ],
    "challengesFaced": [
      "Implementing smooth and responsive animations across different screen sizes",
      "Integrating Chart.js for multiple visualization types without performance issues",
      "Ensuring calendar integration synced properly with study hour tracking"
    ],
    "futureScope": [
      "Add authentication and user profiles",
      "Enable real-time collaboration and study groups",
      "Integrate AI-based course recommendations based on user performance"
    ]
  },
  {
    "name": "Seva Samarth",
    "headline": "A comprehensive elder care platform UI built with HTML, CSS, and JavaScript.",
    "category": ["Web Development", "UI/UX", "Healthcare"],
    "problemStatement": "Creating a user-friendly, accessible, and responsive interface for an elder care platform that connects seniors with professional caregivers and essential support services.",
    "solutionApproach": "Designed an interactive home page, service showcase, and care booking interface using HTML and CSS for structure and styling, and JavaScript for dynamic interactivity. Focused on clarity, accessibility, and trust-building through intuitive navigation and clear service information.",
    "startDate": "2024-03",
    "endDate": "2024-03",
    "status": "Under Development",
    "githubUrl": "https://github.com/Mohammad-Ehshan/seva_samarth",
    "liveUrl": "https://seva-samarth.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/sevasamarth.png"],
    "tags": ["HTML5", "CSS3", "JavaScript", "UI/UX", "Healthcare", "Elder Care"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [
      {
        "name": "Anita Verma",
        "feedback": "Seva Samarth's interface is so easy to navigate. My parents were able to explore the services without any confusion."
      },
      {
        "name": "Ravi Sharma",
        "feedback": "I appreciate the clarity in service details. It feels professional, trustworthy, and elder-friendly."
      }
    ],
    "challengesFaced": [
      "Designing a layout that caters to elderly users with limited tech familiarity",
      "Ensuring text readability and high contrast for accessibility",
      "Balancing professional aesthetics with a warm, approachable feel"
    ],
    "futureScope": [
      "Integrate an online caregiver booking and scheduling system",
      "Add user authentication and caregiver profiles",
      "Implement real-time chat support for inquiries",
      "Mobile-responsive optimization for easier access"
    ]
  },
  {
    "name": "Swadeshi Scan",
    "headline": "QR-powered platform showing product impact on India's economy",
    "category": ["E-commerce", "Social Impact"],
    "problemStatement": "Consumers lack information about how purchases impact local economy.",
    "solutionApproach": "Uses QR codes to reveal product impact data on jobs, taxes, and environment.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/Swadeshi-Scan",
    "liveUrl": "https://swadeshi-scan.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/swadeshiscan1.png"],
    "tags": ["Next.js", "shadcn/ui", "Tailwind CSS", "Gemini"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "MathMate",
    "headline": "A sleek and responsive calculator built with HTML, CSS, and JavaScript.",
    "category": ["Web Development", "Utility"],
    "problemStatement": "Many online calculators lack responsive design and an intuitive interface, making them less user-friendly across different devices.",
    "solutionApproach": "Designed a clean and responsive calculator UI using HTML and CSS, and implemented all essential arithmetic operations with JavaScript for smooth and instant calculations.",
    "startDate": "2024-06-15",
    "endDate": "2024-06-15",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Calculator",
    "liveUrl": "https://calculator-ehshan.netlify.app",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/mathmate.jpg"],
    "tags": ["HTML", "CSS", "JavaScript", "Calculator", "Responsive Design"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [
      {
        "name": "David Carter",
        "feedback": "MathMate is quick, accurate, and works flawlessly across my phone and laptop."
      },
      {
        "name": "Sophia Lee",
        "feedback": "I love the clean design — it makes doing calculations feel effortless."
      }
    ],
    "challengesFaced": [
      "Ensuring precise floating-point arithmetic in JavaScript.",
      "Making the UI responsive for both mobile and desktop users."
    ],
    "futureScope": [
      "Add advanced scientific functions.",
      "Implement a history log for past calculations.",
      "Provide multiple theme options for better customization."
    ]
  },
  {
    "name": "PowerOn Gym",
    "headline": "A website for a gym client built with Next.js.",
    "category": ["Web Development", "Fitness"],
    "problemStatement": "Designing a visually appealing and responsive website for a gym with modern frameworks.",
    "solutionApproach": "Used Next.js for a fast and SEO-friendly gym website.",
    "startDate": "2025-07",
    "endDate": "2025-07",
    "status": "Completed",
    "githubUrl": "https://github.com/uzumaki-ak/gym-web-client",
    "liveUrl": "https://anikesh-elite-asignment.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/poweron.png"],
    "tags": ["Next.js", "Gym", "Website"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Reframe",
    "headline": "Platform for documenting and sharing philosophical evolution",
    "category": ["Social", "Philosophy"],
    "problemStatement": "People need a way to track and share how their beliefs and perspectives change over time.",
    "solutionApproach": "Provides tools to document belief changes, compare before/after views, and engage with a community.",
    "startDate": "",
    "endDate": "",
    "status": "Completed",
    "githubUrl": "https://github.com/uzumaki-ak/-Reframe",
    "liveUrl": "https://reframe-two.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/reframe1.png"],
    "tags": ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Prisma"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Think Tank",
    "headline": "MERN blog application with admin panel",
    "category": ["Blog", "CMS"],
    "problemStatement": "Need for a customizable blog platform with admin controls.",
    "solutionApproach": "Provides a full-featured blog with admin panel using MERN stack.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/think-tank",
    "liveUrl": "https://raghavblogs.onrender.com/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/thinktank1.png"],
    "tags": ["MERN", "MongoDB", "Express", "React", "Node.js"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Spotify Player",
    "headline": "Redesigned Spotify player with HTML, CSS, JavaScript, and Spotify API.",
    "category": ["Web Development", "Music"],
    "problemStatement": "Enhancing Spotify's design and functionality with a custom player.",
    "solutionApproach": "Used HTML/CSS/JS for UI and integrated Spotify API for music playback.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/spotify-player",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/spotifyplayer1.png", "/projects/spotifyplayer2.png"],
    "tags": ["HTML", "CSS", "JavaScript", "Spotify API"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "EcoFleetSim",
    "headline": "Delivery robotics and EV simulation platform",
    "category": ["Simulation", "Logistics"],
    "problemStatement": "Companies need to test delivery strategies without physical hardware.",
    "solutionApproach": "Simulates delivery robots and EVs for route planning and performance analysis.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/hackemnon-robotics",
    "liveUrl": "",
    "demoVideo": "https://www.youtube.com/watch?v=F8UYeIvWNjo",
    "pptImages": [],
    "projectImages": ["/projects/ecofleet1.png"],
    "tags": ["React", "Tailwind CSS", "Leaflet.js", "Next.js", "Supabase"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Market Agency",
    "headline": "Market agency website for a client",
    "category": ["Marketing", "Website"],
    "problemStatement": "Agency needs professional online presence.",
    "solutionApproach": "Provides a modern website showcasing agency services.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/market-agency",
    "liveUrl": "https://ak-agency.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/akagency1.png"],
    "tags": ["Next.js", "Accernity"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Dharika",
    "headline": "Pre-launch landing page for an Indian ethnic fashion brand",
    "category": ["Fashion", "E-commerce"],
    "problemStatement": "Need to build brand awareness and collect early supporters before launch.",
    "solutionApproach": "Interactive landing page with email capture and gamification to engage potential customers.",
    "startDate": "",
    "endDate": "",
    "status": "Under Development",
    "githubUrl": "https://github.com/uzumaki-ak/dharika-assign",
    "liveUrl": "https://dharika-assign.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/dharika1.png","projects/dharika2.png"],
    "tags": ["React", "TypeScript", "Tailwind CSS"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Tic Tac Toe",
    "headline": "A classic Tic Tac Toe game built with HTML, CSS, and JavaScript.",
    "category": ["Game", "Web Development"],
    "problemStatement": "Creating an interactive and responsive Tic Tac Toe game for web browsers.",
    "solutionApproach": "Implemented a simple UI with HTML/CSS and game logic with JavaScript.",
    "startDate": "2025-02",
    "endDate": "2025-02",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/TIC_TAC_TOE",
    "liveUrl": "https://tic-tac-toe-ehshan.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/tictactoe.png"],
    "tags": ["HTML", "CSS", "JavaScript", "Game"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [""],
    "futureScope": []
  },
  {
    "name": "Rock Paper Scissor",
    "headline": "A Rock Paper Scissor game built with HTML, CSS, and JavaScript.",
    "category": ["Game", "Web Development"],
    "problemStatement": "Creating an interactive and responsive Rock Paper Scissor game for web browsers.",
    "solutionApproach": "Implemented a simple UI with HTML/CSS and game logic with JavaScript.",
    "startDate": "2024-03",
    "endDate": "2024-03",
    "status": "",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Rock-Paper-Scissor-Game",
    "liveUrl": "https://rock-paper-scissor-ehshan.netlify.app",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/rockpaperscissors.png"],
    "tags": ["HTML", "CSS", "JavaScript", "Game"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Atomix",
    "headline": "A website for a hotel built with HTML and CSS.",
    "category": ["Web Development", "Hospitality"],
    "problemStatement": "Designing a visually appealing and responsive website for a hotel.",
    "solutionApproach": "Used HTML for structure and CSS for styling to create a modern hotel website.",
    "startDate": "2023-10",
    "endDate": "2023-10",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Hotel-Website",
    "liveUrl": "https://hotel-ehshan.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/atomix.png"],
    "tags": ["HTML", "CSS", "Hotel", "Website"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Star Fitness",
    "headline": "A website for our gym Star Fitness built with HTML and CSS.",
    "category": ["Web Development", "Fitness"],
    "problemStatement": "Designing a visually appealing and responsive website for a gym.",
    "solutionApproach": "Used HTML for structure and CSS for styling to create a modern gym website.",
    "startDate": "2023-09",
    "endDate": "2023-09",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Gym-Website",
    "liveUrl": "https://gym-ehshan.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/starfitness.png"],
    "tags": ["HTML", "CSS", "Gym", "Website"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Amazon",
    "headline": "A clone of Amazon's website built with HTML and CSS.",
    "category": ["Web Development", "E-commerce"],
    "problemStatement": "Replicating the Amazon website's UI with HTML and CSS.",
    "solutionApproach": "Used HTML for structure and CSS for styling to mimic Amazon's design.",
    "startDate": "2023-11",
    "endDate": "2023-12",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Amazon",
    "liveUrl": "https://amozon-ehshan.netlify.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/amazon.png"],
    "tags": ["HTML", "CSS", "Amazon", "Clone"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Bumblebees School",
    "headline": "Website for a playschool with playful frontend design",
    "category": ["Education", "Website"],
    "problemStatement": "Playschools need an engaging online presence to attract parents.",
    "solutionApproach": "Provides a playful, interactive website showcasing the playschool's offerings.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/bumblebees--school",
    "liveUrl": "https://bumblebees-school.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/bumblebees1.png"],
    "tags": ["Next.js"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Flash Chat",
    "headline": "WhatsApp messaging tool without saving contacts",
    "category": ["Communication"],
    "problemStatement": "Need to chat on WhatsApp without saving contacts.",
    "solutionApproach": "Enables chatting with any number via QR code without saving contacts.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/flash-chat",
    "liveUrl": "https://whatsapp-flash-chat.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/flashchat1.png"],
    "tags": ["React", "JavaScript", "Bootstrap"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Carbon Footprint Calculator",
    "headline": "Tool to calculate carbon footprint",
    "category": ["Environment"],
    "problemStatement": "People need awareness of their environmental impact.",
    "solutionApproach": "Calculates carbon footprint based on user inputs.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/carbonfootprintCalc",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["React"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Currency Converter",
    "headline": "A currency converter built with HTML, CSS, and JavaScript.",
    "category": ["Web Development", "Utility"],
    "problemStatement": "Creating a tool to convert currencies in real-time.",
    "solutionApproach": "Used HTML/CSS for UI and JavaScript for conversion logic and API integration.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Currency-Convertor",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["HTML", "CSS", "JavaScript", "Currency"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
   {
    "name": "StockLens",
    "headline": "A platform showing graphs and data for stock investments built with Next.js.",
    "category": ["Finance", "Web Development"],
    "problemStatement": "Providing users with a visual representation of stock data for better investment decisions.",
    "solutionApproach": "Used Next.js for the frontend and integrated APIs for stock data.",
    "startDate": "2025-02-15",
    "endDate": "2025-02-16",
    "status": "Completed",
    "githubUrl": "https://github.com/Mohammad-Ehshan/Stock-Invetment",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["Next.js", "Stock", "Investment", "Graphs"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Functional Login Page",
    "headline": "Fully functional login page",
    "category": ["Authentication"],
    "problemStatement": "Need for a working login system.",
    "solutionApproach": "Provides a login page with HTML, CSS, and JavaScript.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/working-login-page-",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["HTML", "CSS", "JavaScript"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Previous Portfolio",
    "headline": "Personal portfolio website",
    "category": ["Portfolio"],
    "problemStatement": "Need to showcase personal projects and skills.",
    "solutionApproach": "Provides a portfolio website built with Next.js.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/portfollio",
    "liveUrl": "https://portfollio-red.vercel.app/",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": ["/projects/oldportfolio1.png"],
    "tags": ["Next.js"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Old Portfolio",
    "headline": "Previous version of personal portfolio",
    "category": ["Portfolio"],
    "problemStatement": "Need to showcase previous work and skills.",
    "solutionApproach": "Provides a portfolio website.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/old-portfolio",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": [],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  },
  {
    "name": "Ulta Edit Clone",
    "headline": "Clone of Ulta Edit using HTML and CSS",
    "category": ["Clone", "UI"],
    "problemStatement": "Practice recreating existing interfaces.",
    "solutionApproach": "Clones the Ulta Edit interface using HTML and CSS.",
    "startDate": "",
    "endDate": "",
    "status": "",
    "githubUrl": "https://github.com/uzumaki-ak/ultra-edit-clone",
    "liveUrl": "",
    "demoVideo": "",
    "pptImages": [],
    "projectImages": [],
    "tags": ["HTML", "CSS"],
    "blogUrl": "",
    "feedbackForm": "",
    "testimonials": [],
    "challengesFaced": [],
    "futureScope": []
  }
]